function Lzz = D2LDzz(in1)
%D2LDZZ
%    LZZ = D2LDZZ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    03-Dec-2021 10:24:46

z4 = in1(:,4);
z5 = in1(:,5);
t2 = -z5;
t3 = t2+z4+1.0;
t4 = 1.0./t3.^2;
t5 = t4.*(9.6e+1./5.0);
t6 = -t5;
Lzz = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t5,t6,0.0,0.0,0.0,0.0,t6,t5+1.0./(z5+1.0).^2.*1.8e+1,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
