function Lz = DLDz(in1)
%DLDZ
%    LZ = DLDZ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    03-Dec-2021 10:24:45

z4 = in1(:,4);
z5 = in1(:,5);
t2 = -z5;
t3 = t2+z4+1.0;
t4 = 1.0./t3;
t5 = t4.*(9.6e+1./5.0);
Lz = [5.0,6.0,8.0,-t5+1.0e+1,t5-1.8e+1./(z5+1.0),-7.0];
