function C = valC(in1)
%VALC
%    C = VALC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    03-Dec-2021 10:24:45

z1 = in1(:,1);
z2 = in1(:,2);
z3 = in1(:,3);
z4 = in1(:,4);
z5 = in1(:,5);
z6 = in1(:,6);
t2 = z5+1.0;
t4 = -z4;
t5 = -z5;
t3 = log(t2);
t6 = t5+z4+1.0;
t7 = log(t6);
C = [t3.*(-4.0./5.0)-t7.*(2.4e+1./2.5e+1)+z6.*(4.0./5.0);t4+z5;z1.*-2.0+z5;t5-z2.*2.0+z4;-t3-t7.*(6.0./5.0)+z3.*2.0+z6-2.0;z1+z2-1.0;t4;t5;-z6;z4-2.0;z5-2.0;z6-1.0;-z1;-z2;-z3;z1-1.0;z2-1.0;z3-1.0];
