function L = valL(in1)
%VALL
%    L = VALL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    03-Dec-2021 10:24:44

z1 = in1(:,1);
z2 = in1(:,2);
z3 = in1(:,3);
z4 = in1(:,4);
z5 = in1(:,5);
z6 = in1(:,6);
L = z1.*5.0+z2.*6.0+z3.*8.0+z4.*1.0e+1-z6.*7.0-log(z4-z5+1.0).*(9.6e+1./5.0)-log(z5+1.0).*1.8e+1+1.0e+1;
